#!/bin/bash

[ -z "$BASE_IMAGE_TAG" ] && BASE_IMAGE_TAG=drupal-acquia-php-7.3

docker build \
    --build-arg BASE_IMAGE_TAG="$BASE_IMAGE_TAG" \
    -f "$DOCKERFILE_PATH" \
    -t "$IMAGE_NAME" \
    .
